/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DeviceObject {
  macAddress: string
  serialNumber: string
}
export interface MachineObject {
  key: string
  nonce: string
  deviceId: string
}
export function sum(a: number, b: number): number
export function uuidV4(): string
export function getSysInfo(): object
export function getMachineId(pem: string): object
export function decryptDeviceId(pem: string, deviceId: string, key: string, nonce: string): object
